---
- name: macOS configuration # noqa: name[casing]
  hosts: localhost
  connection: local
  become: false


  vars:
    enable_ssh_config: true
    enable_hosts_entries: true
    enable_macos_tweaks: true
    hosts_entry_sources:
      - templates/blocked_domains.j2
  handlers:
    - name: Flush DNS cache
      become: true
      ansible.builtin.command: killall -HUP mDNSResponder
      changed_when: false

  pre_tasks:
    - name: End play if not macOS
      ansible.builtin.meta: end_play
      when: ansible_facts['os_family'] != 'Darwin'

  tasks:
    - name: SSH config
      ansible.builtin.include_tasks: tasks/common/ssh-config.yml

    - name: Manage /etc/hosts entries (Declarative)
      when: enable_hosts_entries
      ansible.builtin.include_tasks: tasks/common/hosts-entries.yml

    - name: macOS system tweaks # noqa: name[casing]
      when: enable_macos_tweaks
      ansible.builtin.include_tasks: tasks/darwin/system-tweaks.yml
